version: "3"
services:
    daphne-postgres:
        image: postgres
        container_name: daphne-postgresql
        ports:
            - "5432:5432"
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: ${DOCKER_DATABASE_USER}
            POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
            POSTGRES_DB: ${DOCKER_DATABASE_NAME}
        volumes:
            - ./postgresql-data:/var/lib/postgresql/data
    daphne-influxdb:
        container_name: daphne-influxdb
        image: influxdb
        ports:
            - 8086:8086
        volumes:
            - ./influxdb-data:/var/lib/influxdb
        env_file:
            - .env
        restart: unless-stopped
        environment:
            INFLUXDB_DB: ${DOCKER_INFLUXDB_NAME}
            INFLUXDB_ADMIN_USER: ${DOCKER_INFLUXDB_USER}
            INFLUXDB_ADMIN_PASSWORD: ${DOCKER_INFLUXDB_PASSWORD}
volumes:
    postgresql-data:
    influxdb-data:
    chronograf-storage:
